### ISSUE TITLE
想问下文章中的baseline1,也就是最简单的DerainNet

### ISSUE THREAD

**Issue by booker-max** [zsyOAOA/S2VD#13]
![image](https://user-images.githubusercontent.com/74257220/141675885-d952084f-17b7-4987-a4a7-b7064ff81e81.png)
您好，可以简单地解释一下这个网络么，例如紫色的那个减号的作用是减去雨层么，我可以认为第二个pixel-shuffle模块输出的是rain_streak么？

**Comment by zsyOAOA** [comment]
@booker-max Pixel-Shuffle输出的是雨层，减号表示原图减去雨层得到干净的背景图，最后三个卷积层是对背景finetune

**Comment by booker-max** [comment]
好的，谢谢您。
