### ISSUE TITLE
您好，我想问一下关于rain streak具体是如何得到的

### ISSUE THREAD

**Issue by BinLi-git** [zsyOAOA/S2VD#14]
您好，看到您补充材料里关于rain streak的叙述，但是自己相减得到的rain streak结果并不是很理想，可能在代码里漏掉了一些细节，请问关于这一部分的代码可以提供一下吗？非常感谢，祝工作顺利，阖家幸福。

**Comment by zsyOAOA** [comment]
@BinLi-git RGB三个通道取了最大值

**Comment by BinLi-git** [comment]
得到的Rain streak是单通道的吗，还是RGB三个通道都取最大值的三通道图

**Comment by zsyOAOA** [comment]
文章里的实验都是直接相减的。。。如果感觉直接相减得到的rain_streak不理想，可以尝试RGB三个通道取最大值，使用单通道的rain streak.

**Comment by BinLi-git** [comment]
好的谢谢 @zsyOAOA
