### ISSUE TITLE
和Table 1相比PSNR低了两个点

### ISSUE THREAD

**Issue by Zhang-Jing-Xuan** [zsyOAOA/S2VD#17]
我从头开始训练了47轮，结果和论文中的表1相比，PSNR低了将近2个点，请问是什么原因造成的呢？谢谢。
<img width="199" alt="result" src="https://user-images.githubusercontent.com/70561649/194974226-5a5681d9-5234-4b62-b195-48324da8ab6b.png">

**Comment by zsyOAOA** [comment]
论文里的指标是在Y通道上计算的。

**Comment by Zhang-Jing-Xuan** [comment]
我觉得应该不是评测的问题。因为我使用您发布的./model_states/derainer_rho05.pt模型测试是可以达到论文的结果的。但是我自己从头训练却低了2个点。

**Comment by zsyOAOA** [comment]
先确定你是在RGB还是Y通道上计算的指标？

**Comment by zsyOAOA** [comment]
zsyzam@gmail, 你给我发封邮件，然后加我微信说吧

**Comment by Zhang-Jing-Xuan** [comment]
ok
