### ISSUE TITLE
Question about latent_dir_name

### ISSUE THREAD

**Issue by LuPaoPao** [zsyOAOA/S2VD#3]
FileNotFoundError: [Errno 2] No such file or directory:  /**/**/**/latent_eps6_rho05_tv112
I can't find latent_eps6_rho05_tv112, and don't know how to generate it.

**Comment by zsyOAOA** [comment]
Such latent folder will be automatically generated when intializing the model.

**Comment by LuPaoPao** [comment]
Thanks for your reply，and I have solved this problem:


        if make_latent:
            if latent_dir.exists():
                shutil.rmtree(str(latent_dir))
            latent_dir.mkdir()

be revised as:

import os
        if make_latent:
            if os.path.exists(latent_dir):
                os.remove(latent_dir)
            os.makedirs(latent_dir)
