### ISSUE TITLE
About the derainer network

### ISSUE THREAD

**Issue by sfwang20** [zsyOAOA/S2VD#5]
Hello! Thanks for your excellent work.
I wonder about the network architecture of the derainer f(-;w) in Figure 2. of your paper:
Why does it need to minus original image after the Pixel-Shuffle layer ?
Thank you.

**Comment by zsyOAOA** [comment]
Note that the Pixel-shuffle layer outputs the rain layer. The original rainy image minuses the output rain layer to obtain the rain-free image.
