### ISSUE TITLE
训练GPUs和训练时间

### ISSUE THREAD

**Issue by dongfengxijian** [zsyOAOA/S2VD#8]
您好，我想请问一下训练这个去雨算法需要几块多大显存的GPUs以及大概的训练时间。谢谢分享。

**Comment by zsyOAOA** [comment]
需要使用的GPU显存很小，文章里的实验是在单卡1080Ti上完成了，时间大概三四天吧，我记不太清楚了 @dongfengxijian

**Comment by dongfengxijian** [comment]
@zsyOAOA 感谢你的分享。
