### ISSUE TITLE
about the deraining result

### ISSUE THREAD

**Issue by whyandbecause** [zsyOAOA/S2VD#9]
you claim "Such a gap between synthetic and real data sets results in poor performance when applying them to real scenarios. To address these issues, this paper proposes a new semi-supervised video deraining method " in your paper, but i can't found it is suitable for real scenarios from the results attaching on your paper. Why is this happening? thank you.

**Comment by zsyOAOA** [comment]
@whyandbecause As shown in the paper (limitation subsection), our method indeed can't handle the real heavy rain case well. I guess it is mainly owning to the used unlabelled real data in NTURain data set, which is with large motion between adjacent frames. However, the adopted 3D Markov Random Field prior is not very suitable in such case.

By the way,  I'm still seeking for better image prior for the unlabelled real data. If you are interested, we can have a further discussion or collaboration to solve this problem.

Thanks for your attention to my work.

**Comment by whyandbecause** [comment]
Thank you for your reply. It is really a difficult problem to remove the rain layer in the real scenes. I‘m looking forward to your better solution, thank you
